###  Debe devolver un código 404 con un message
GET http://localhost:3000/

### Debe devolver un JSON con los usuarios

GET http://localhost:3000/users

### Debe devolver un JSON con tarjetas

GET http://localhost:3000/cards

### Debe devolver un JSON de usuario nada más

GET http://localhost:3000/users/8340d0ec33270a25f2413b69

### Debe devolver un JSON de error por que no existe el usuario
GET http://localhost:3000/users/no_existe
