
### Debe devolver un JSON con tarjetas
GET http://localhost:3000/cards

### Crear una tarjeta
POST http://localhost:3000/cards
Content-Type: application/json

{
  "name": "Gatoo negro",
  "link": "https://i.pinimg.com/736x/13/4f/81/134f8118c299fc1ccba3b320ce0bec70.jpg"
}

### Borrar una tarjeta
DELETE http://localhost:3000/cards/

### Dar Like a tarjeta
PUT http://localhost:3000/cards/66f4ce07f735aa1883c94c07/likes


### Quitar like a tarjeta
DELETE http://localhost:3000/cards/66f4ce07f735aa1883c94c07/likes